<a href="https://colab.research.google.com/github/Vigneswarsiddu/Important-Python-Libraries-for-Machine-Learning/blob/main/Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Author: K. VIGNESWAR SIDDU Email ID: vigneswarsiddu07@gmail.com**

NumPy - Numerical Python

Advantages:
1. It allows several mathematical Operations
2. The Operations we do in NumPy array it is faster

In [1]:
#Loading library
import numpy as np

# List vs Numpy - Time Taken

In [2]:
# Loading the time
from time import process_time

Time taken by the List

In [16]:
#let's create list from 0 to 10000
my_list=[i for i in range(10000)]
start_time=process_time()
print("The start time is: ",start_time)
#lets add +5 into the list
my_list=[i+5 for i in my_list]
end_time=process_time()
print("the end time is: ",end_time)

#difference
print(end_time-start_time)


The start time is:  15.683412128
the end time is:  15.686739126
0.0033269980000003585


Time Taken by Numpy Array

In [17]:
np_array=np.array([i for i in range(10000)])
start_time1=process_time()
print("The start time is: ",start_time1)
np_array+=5
end_time1=process_time()
print("the end time is: ",end_time1)

#difference
print(end_time1-start_time1)

#In output we can see compare to list numpyarray taking time is very less as 1.8 ms

The start time is:  16.011505706
the end time is:  16.01331606
0.0018103539999998475


# Numpy Arrays

In [19]:
#creating the list
list1=[1,2,3,4,5,6,7,8,9]
print(type(list1))
print(list1)

<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [20]:
np_array=np.array([1,2,3,4,5,6,7,8,9])
print(type(np_array))
print(np_array)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [21]:
#creating an 1D array
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [22]:
x.shape

(4,)

In [24]:
#creating an 2D array
y=np.array([(1,2,3,4),(5,6,7,8)])
print(y)
y.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [25]:
z=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(z)
z.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

In [27]:
#To create array in floating point
a=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(a)
print(a.shape)
print(type(a))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
(2, 4)
<class 'numpy.ndarray'>


Initial Placeholders in Numpy arrays

In [32]:
#creating the numpy array with 0's

b=np.zeros((4,4),dtype=int)
print(b)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [30]:
#creating with 1's

c=np.ones((4,4),dtype=int)
print(c)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [33]:
# creating with particular value

d=np.full((4,4),5)
print(d)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [61]:
#creating an Identity Matrix

e=np.eye(4,dtype=int)
print(e)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [43]:
#creating random values
f=np.random.random((4,4))
print(f)

[[0.22397617 0.80977149 0.66789341 0.86700773]
 [0.53792696 0.29628436 0.89399435 0.49302727]
 [0.20346914 0.40771786 0.698909   0.58151559]
 [0.23001698 0.24144416 0.97864581 0.83636154]]


In [45]:
g=np.random.randint(10,20,(4,4))
print(g)

[[15 12 13 19]
 [13 17 11 18]
 [12 17 10 14]
 [19 15 17 12]]


In [56]:
#creating an array of evenly spaced values

h=np.linspace(10,20,6)
print(h)
h.shape

[10. 12. 14. 16. 18. 20.]


(6,)

In [60]:
#creating an array of evenly spaced values with slicing - step
i=np.arange(2,100+2,2)
print(i)
print(len(i))

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
50


In [62]:
#converting list into Numpy Array
siddu=[1,2,3,4,5,6,7,8,9]
type(siddu)
np_array=np.asarray(siddu)
print(np_array)
type(np_array)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

# Analyzing an Numpy Array

In [63]:
df=np.random.randint(10,20,(4,4))
print(df)

[[13 11 11 18]
 [15 17 18 13]
 [11 10 15 12]
 [15 14 16 11]]


In [64]:
# check dimension
print(df.shape)

(4, 4)


In [65]:
# no.of Dimension
print(df.ndim)

2


In [66]:
# no.of values present in array
print(df.size)

16


In [68]:
# datatype of value
print(df.dtype)

int64


# Mathematical Operations on Numpy Array

In [71]:
#Element wise addition
x=np.random.randint(10,20,(4,4))
y=np.random.randint(20,30,(4,4))
z=np.random.randint(30,40,(4,4))
print(x,y,z)

[[16 19 15 10]
 [18 17 18 16]
 [13 11 10 13]
 [12 19 13 15]] [[26 28 25 20]
 [25 28 22 26]
 [26 26 26 20]
 [24 22 28 20]] [[37 33 38 32]
 [31 33 35 33]
 [31 37 35 30]
 [36 31 38 37]]


In [72]:
print("The sum is: ",x+y+z)
print("The product is: ",x*y*z)
print("The subtraction is: ",x-y-z)

The sum is:  [[79 80 78 62]
 [74 78 75 75]
 [70 74 71 63]
 [72 72 79 72]]
The product is:  [[15392 17556 14250  6400]
 [13950 15708 13860 13728]
 [10478 10582  9100  7800]
 [10368 12958 13832 11100]]
The subtraction is:  [[-47 -42 -48 -42]
 [-38 -44 -39 -43]
 [-44 -52 -51 -37]
 [-48 -34 -53 -42]]


In [73]:
#Element wise addition
x=np.random.randint(10,20,(4,4))
y=np.random.randint(20,30,(4,4))
z=np.random.randint(30,40,(4,4))
print(x,y,z)

[[18 11 16 11]
 [14 13 19 13]
 [14 13 11 11]
 [16 18 18 11]] [[21 25 21 28]
 [25 25 24 21]
 [21 21 27 21]
 [28 24 25 20]] [[36 30 39 38]
 [31 37 37 39]
 [37 30 34 34]
 [39 38 32 32]]


In [77]:
print(np.add(x,y,z))
print(np.subtract(x,y,z))
print(np.multiply(x,y,z))
print(np.divide(x,y))
print(np.divide(y,z))

[[399 300 357 336]
 [375 350 480 294]
 [315 294 324 252]
 [476 456 475 240]]
[[357 250 315 280]
 [325 300 432 252]
 [273 252 270 210]
 [420 408 425 200]]
[[ 7938  6875  7056  8624]
 [ 8750  8125 10944  5733]
 [ 6174  5733  8019  4851]
 [12544 10368 11250  4400]]
[[18. 11. 16. 11.]
 [14. 13. 19. 13.]
 [14. 13. 11. 11.]
 [16. 18. 18. 11.]]
[[0.0026455  0.00363636 0.00297619 0.00324675]
 [0.00285714 0.00307692 0.00219298 0.003663  ]
 [0.00340136 0.003663   0.003367   0.004329  ]
 [0.00223214 0.00231481 0.00222222 0.00454545]]


# Array Manipulation

In [79]:
my_array=np.random.randint(10,20,(4,3))
print(my_array)
print(my_array.shape)
print(type(my_array))
print(my_array.ndim)
print(my_array.size)

[[19 19 15]
 [13 19 14]
 [15 17 12]
 [18 11 18]]
(4, 3)
<class 'numpy.ndarray'>
2
12


In [80]:
#transpose an array
trans=np.transpose(my_array)
print(trans)
print(trans.shape)

[[19 13 15 18]
 [19 19 17 11]
 [15 14 12 18]]
(3, 4)


In [81]:
# or you can simply use T
my_array=np.random.randint(10,20,(4,3))
print(my_array)
trans1=my_array.T
print(trans1)

[[17 11 12]
 [18 19 11]
 [13 10 14]
 [13 12 17]]
[[17 18 13 13]
 [11 19 10 12]
 [12 11 14 17]]


In [82]:
#reshaping of an array
s=np.random.randint(0,10,(4,3))
print(s)

[[6 9 7]
 [4 6 5]
 [1 3 3]
 [4 7 2]]


In [84]:
i=s.reshape(2,6)
print(i)

[[6 9 7 4 6 5]
 [1 3 3 4 7 2]]
